package com.gilandeddy.pocketmovie.model;

import java.util.ArrayList;

/**
 * @author Gilbert & Eddy
 * This class SearchedMovies returns the searched movies object arraylist generated by
 * search query in the SearchActivity
 */

/**
 *
 */
public class SearchedMovies {
    private static final SearchedMovies ourInstance = new SearchedMovies();
    private ArrayList<Movie> movies = new ArrayList<>();

    /**
     *
     * @return
     */
    public static SearchedMovies getInstance() {
        return ourInstance;
    }

    /**
     *
     */
    private SearchedMovies() {
    }

    /**
     *
     * @param newMovies
     */
    public void addToSearchedMovies(ArrayList<Movie> newMovies) {
        movies.addAll(newMovies);

    }

    /**
     *
     * @return
     */
    public ArrayList<Movie> getSearchedMovies() {
        return movies;
    }
}
